import { Product } from '@/types/product';

/**
 * Product data for shop/prints
 */
export const products: Product[] = [
  {
    id: 'print-001',
    title: 'Chocolate Milkshake Print',
    description: 'Premium quality food photography print showcasing rich chocolate milkshake with perfect lighting.',
    price: 2499,
    image: '/images/Photography/Chocolate_Milkshake.jpg',
    category: 'print',
    tags: ['beverages', 'milkshake', 'chocolate', 'drinks'],
    featured: true,
    inStock: true,
    dimensions: '12" x 18" (30cm x 45cm)',
    link: '/shop/print-001',
  },
  {
    id: 'print-002',
    title: 'Coffee Scoop Fine Art Print',
    description: 'Delicious coffee ice cream scoop captured in stunning detail. Perfect for cafe decor.',
    price: 2199,
    image: '/images/Photography/Coffee_Scoop.jpg',
    category: 'print',
    tags: ['desserts', 'ice-cream', 'coffee', 'food'],
    featured: true,
    inStock: true,
    dimensions: '16" x 20" (40cm x 50cm)',
    link: '/shop/print-002',
  },
  {
    id: 'print-003',
    title: 'Cookies & Cream Milkshake',
    description: 'Eye-catching cookies and cream milkshake photography, perfect for restaurant menus.',
    price: 2499,
    image: '/images/Photography/CookiesCream_Milkshake.jpg',
    category: 'print',
    tags: ['beverages', 'milkshake', 'cookies', 'dessert'],
    featured: false,
    inStock: true,
    dimensions: '12" x 18" (30cm x 45cm)',
    link: '/shop/print-003',
  },
  {
    id: 'print-004',
    title: 'Strawberry Scoop Print',
    description: 'Vibrant strawberry ice cream scoop with perfect texture and color. Gallery quality.',
    price: 2199,
    image: '/images/Photography/Strawberry_Scoop.jpg',
    category: 'print',
    tags: ['desserts', 'ice-cream', 'strawberry', 'colorful'],
    featured: false,
    inStock: true,
    dimensions: '16" x 20" (40cm x 50cm)',
    link: '/shop/print-004',
  },
  {
    id: 'print-005',
    title: 'Kiwi Milkshake Art Print',
    description: 'Fresh and vibrant kiwi milkshake perfect for summer-themed decor.',
    price: 2299,
    image: '/images/Photography/Kiwi_Milkshake.jpg',
    category: 'print',
    tags: ['beverages', 'milkshake', 'kiwi', 'fresh', 'green'],
    featured: false,
    inStock: true,
    dimensions: '12" x 18" (30cm x 45cm)',
    link: '/shop/print-005',
  },
  {
    id: 'print-006',
    title: 'Red Velvet Dessert Print',
    description: 'Decadent red velvet dessert photography with mouth-watering detail.',
    price: 2399,
    image: '/images/Photography/Redvelvet.jpg',
    category: 'print',
    tags: ['desserts', 'red-velvet', 'cake', 'luxury'],
    featured: false,
    inStock: true,
    dimensions: '16" x 20" (40cm x 50cm)',
    link: '/shop/print-006',
  },
  {
    id: 'print-007',
    title: 'Pineapple Milkshake Print',
    description: 'Tropical pineapple milkshake captured with professional lighting and styling.',
    price: 2499,
    image: '/images/Photography/Pineapple_Milkshake.jpg',
    category: 'print',
    tags: ['beverages', 'milkshake', 'pineapple', 'tropical'],
    featured: false,
    inStock: true,
    dimensions: '12" x 18" (30cm x 45cm)',
    link: '/shop/print-007',
  },
  {
    id: 'print-008',
    title: 'Masala French Fries',
    description: 'Crispy masala french fries with vibrant spices. Perfect for food business marketing.',
    price: 1999,
    image: '/images/Photography/Masala_FrenchFires.jpg',
    category: 'print',
    tags: ['snacks', 'fries', 'spicy', 'indian'],
    featured: false,
    inStock: true,
    dimensions: '12" x 16" (30cm x 40cm)',
    link: '/shop/print-008',
  },
  {
    id: 'digital-001',
    title: 'Complete Beverage Collection - Digital',
    description: 'High-resolution digital files of all our beverage photography. Commercial license included.',
    price: 15999,
    image: '/images/Photography/Chocolate_Milkshake.jpg',
    category: 'digital',
    tags: ['digital', 'beverages', 'commercial', 'collection'],
    featured: true,
    inStock: true,
    dimensions: 'High-res (4000x6000px)',
    link: '/shop/digital-001',
  },
  {
    id: 'digital-002',
    title: 'Ice Cream Collection - Digital',
    description: 'Premium digital collection of 8 ice cream scoop photographs. Perfect for menus and marketing.',
    price: 12999,
    image: '/images/Photography/Coffee_Scoop.jpg',
    category: 'digital',
    tags: ['digital', 'ice-cream', 'desserts', 'collection'],
    featured: false,
    inStock: true,
    dimensions: 'High-res (4000x6000px)',
    link: '/shop/digital-002',
  },
  {
    id: 'package-001',
    title: 'Restaurant Menu Package',
    description: 'Complete food photography package including 15 custom photos, editing, and usage rights.',
    price: 45000,
    image: '/images/Photography/VeggieLollipops.jpg',
    category: 'package',
    tags: ['package', 'restaurant', 'custom', 'photography'],
    featured: true,
    inStock: true,
    dimensions: 'Custom shoot + 15 photos',
    link: '/shop/package-001',
  },
  {
    id: 'package-002',
    title: 'Social Media Content Package',
    description: '30 professionally styled food photos optimized for Instagram, Facebook, and marketing.',
    price: 35000,
    image: '/images/Photography/Stawberry_Milkshake.jpg',
    category: 'package',
    tags: ['package', 'social-media', 'instagram', 'marketing'],
    featured: false,
    inStock: true,
    dimensions: '30 photos + editing',
    link: '/shop/package-002',
  },
  {
    id: 'service-001',
    title: 'Half-Day Food Photography Session',
    description: 'Professional 4-hour food photography session with styling, lighting, and editing.',
    price: 25000,
    image: '/images/Photography/CookiesCream_Scoop.jpg',
    category: 'service',
    tags: ['service', 'photography', 'session', 'professional'],
    featured: false,
    inStock: true,
    dimensions: '4 hours + 20 photos',
    link: '/shop/service-001',
  },
  {
    id: 'service-002',
    title: 'Full-Day Photography & Styling',
    description: 'Complete full-day (8 hours) food photography with professional food stylist included.',
    price: 45000,
    image: '/images/Photography/Kiwi_Scoop.jpg',
    category: 'service',
    tags: ['service', 'photography', 'styling', 'full-day'],
    featured: true,
    inStock: true,
    dimensions: '8 hours + 40+ photos',
    link: '/shop/service-002',
  },
  {
    id: 'print-009',
    title: 'Veggie Lollipops Print',
    description: 'Colorful and appetizing veggie lollipops perfect for healthy eating campaigns.',
    price: 1999,
    image: '/images/Photography/VeggieLollipops.jpg',
    category: 'print',
    tags: ['snacks', 'vegetables', 'healthy', 'colorful'],
    featured: false,
    inStock: true,
    dimensions: '12" x 16" (30cm x 40cm)',
    link: '/shop/print-009',
  },
  {
    id: 'print-010',
    title: 'Tender Coconut Milkshake',
    description: 'Refreshing tender coconut milkshake with tropical vibes. Summer collection.',
    price: 2299,
    image: '/images/Photography/TenderCoconut_Milkshake.jpg',
    category: 'print',
    tags: ['beverages', 'milkshake', 'coconut', 'tropical', 'healthy'],
    featured: false,
    inStock: true,
    dimensions: '12" x 18" (30cm x 45cm)',
    link: '/shop/print-010',
  },
];
